# Review

## Solving linear system $Ax=b$
* The `solve` function in `numpy.linalg` package
  * `solve(A, b)`
  
### Example
Solve
\begin{align}
x+2y-z &=2\\
2x+y-z & = 2\\
x+y+z & =3
\end{align}

### Define a matrix
* We use the **numpy.array** function to define a matrix
  * it takes a list of lists of the same length
  * each list is a row

In [3]:
from numpy.linalg import solve
from numpy import array

A =array([[1, 2, -1], [2, 1, -1], [1, 1, 1]])
print("A=", A)

b = array([2, 2, 3])
print("b=", b)

A= [[ 1  2 -1]
 [ 2  1 -1]
 [ 1  1  1]]
b= [2 2 3]


In [5]:
x = solve(A, b)
print(x)

[1. 1. 1.]


 ## Polynomial interpolation

* find the unique degree-$n$ polynomial
$$ y = a_0 + a_1 x + a_2 x^2 +\dots a_nx^n $$
that passes through $n+1$ points $\{(x_i,y_i)\}_{i=0}^n$
$$
\left[
\begin{array}{ccccc}
1 & x_0 & x_0^2 & \cdots & x_0^n \\
1 & x_1 & x_1^2 & \cdots & x_1^n \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_n & x_n^2 & \dots & x_n^n
\end{array}
\right]
\left[
\begin{array}{c}
a_0\\
a_1\\
\vdots\\
a_n
\end{array}
\right]
=
\left[
\begin{array}{c}
y_0\\
y_1\\
\vdots\\
y_n
\end{array}
\right]
$$

# Group Assignment Questions

## Question 1

The matrix
$$
\left[\begin{array}{cc}
0.5 & 0.3 & 0\\
0.3 & 0.3 & 0.4\\
0.2 & 0.4 & 0.6 \\
\end{array}\right]
$$
has an eigenvalue $\lambda=1$, find the associated eigenvector which components sum to $1$. Specificaqlly, solve
\begin{align}
0.5x+0.3y & =x\\
0.3x+0.3y +0.4z & =y\\
0.2x + 0.4y + 0.6z &=z\\
x+y+z & =1
\end{align}
 * Hints: 
   * this system is not in the $Ax=b$ form. First rewrite it into the form
   * The solve function requires a square matrix. We have 4 equations. But they are not independent. For example, the sum of the first 3 gives $0=0$. Pick 3 equations out of the 4.

In [9]:
# We pick the second and third equations to solve it.

A = array([[0.3, -0.7, 0.4], [0.2, 0.4, -0.4], [1, 1, 1]])
b = array([0, 0, 1])
solve(A, b)

array([0.20689655, 0.34482759, 0.44827586])

## Question 2
Find the cubic polynomial that passes though $(0, 0)$, $(1, 2)$, $(2, -1)$ and $(3, 1)$, and find an intersection of the polynomial with with $y=1-x$